### ISSUE TITLE
[Feature]: Add code cell option to remove warning/error messages (`warning: false` and `message: false`)

### ISSUE THREAD

**Issue by p0bs** [coatless/quarto-webr#104]
### Feature Description

First things first: many thanks for this wonderful repo!

I was looking through the old and new issues and couldn't find one that relates to using cell options. 

At the moment, the 'hash-pipe' approach doesn't seem to work for me within `webr-r` code cells (using the v0.3.9 tag). For example, I don't seem to be able to remove messages in my output (when it runs the first time).

<br/>

<img width="1512" alt="Screenshot 2023-11-17 at 09 16 06" src="https://github.com/coatless/quarto-webr/assets/8048960/65bf255a-b16e-4a68-8881-949e269ef3f4">
  
---

Ultimately, my question is: Is this a standard case of PICNIC? And, in the unlikely case that it is not, would you be able to add this functionality?

Many thanks again.

**Comment by coatless** [comment]
Thanks for the issue! Right now, we do not receive formatted options from Quarto. So, we have to set up a custom listener on our end for each option that we want to support. With that in mind, there are certain Quarto options we _cannot_ listen for due to where we are in the process, e.g. no support for `echo: false`. c.f. https://github.com/quarto-dev/quarto-cli/discussions/4761

So, is there a set of behaviors that you would find beneficial outside of disabling STDERR? 

Minor note: We likely will not be able to differentiate between `message` and `warning` contexts without submitting an upstream change as the event types we read from the [captureR setup are `stdout` and `stderr`](https://docs.r-wasm.org/webr/latest/evaluating.html#evaluating-r-code-and-capturing-output-with-capturer).

**Comment by p0bs** [comment]
From my perspective (that is only a sample of one), I'm just seeking a way to hide the red under a code chunk. As such, an option to suppress warnings/messages would be great. 

Many thanks again.

**Comment by coatless** [comment]
@p0bs okidokie. I'll modify the title of the issue ticket to clarify the feature request.

We'll probably have a bit more support for this option after #93 is addressed in the next week or so.

**Comment by coatless** [comment]
Addressed in #141
