### ISSUE TITLE
[Q&A]: Is there a way to use quarto-webr code chunks in document rendered by Hugo?

### ISSUE THREAD

**Issue by ClaudiuPapasteri** [coatless/quarto-webr#150]
### What's your question?

Thank you for the excellent extension. It works great when rendered by Quarto into html, but renders to regular unevaluated code chunks when rendered by Hugo. The `.qmd` is first rendered to format `format: hugo-md` and then Hugo renders it to html. 
As per [official docs](https://quarto.org/docs/output-formats/hugo.html), the workflow is:

**index.qmd**   *Quarto =\>*   **index.md**   *Hugo =\>*   **index.html**

A minimal example `.qmd` used with Hugo would look like this:

```
---
title: Minimal example
date: '2024-02-03'
slug: min-eg-slug
categories:
  - R
tags:
  - R
format:
  hugo-md:
    code-fold: false
execute: 
  warning: false
engine: knitr
webr: 
  show-startup-message: false 
filters:
  - webr  
---

```{webr-r}
message <- c(
  "I ran the code chunk",
  "I already knew what was going to happen",
  "I still wanted to test it"
)

sample(message, size = 1)
```

Which renders to identical `.md` and even if I change the `.md`'s yaml format to `format: html`, the html rendered by Hugo will display only a static code chunk:

![image](https://github.com/coatless/quarto-webr/assets/27062887/805aba5c-2c34-42d8-9ba1-880acff133de)

I figure this is an issue with Hugo not knowing how to deal with `{webr-r}`, but is there an elegant solution to this?

Thank you.

**Comment by coatless** [comment]
@ClaudiuPapasteri thanks for the question. So, what's going on here is Hugo is grouped under the output format of `markdown`, not `html`. So, the final output is given as a `.md` instead of `.html`. Thus, when we run our check for supported formats: 

https://github.com/coatless/quarto-webr/blob/1381e3764d0d54a8b51e5d670b0e3765087372dd/_extensions/webr/webr.lua#L529-L533

None of the `webr-r` components are added into the document. If I modify that line to allow the [`markdown` format](https://quarto.org/docs/extensions/lua-api.html), then we get the necessary injections; but, they are not being placed into the "head" of the document. 

<img width="1800" alt="Originating Qmd document to `hugo-md` and the resulting `md` document after rendering." src="https://github.com/coatless/quarto-webr/assets/833642/7da8e48b-5e0d-4735-903e-99e20e2677ec">


This is problematic for our initialization of Monaco Editor. So, I'm not hopeful that this can be extended into `hugo`.

I've spun up a branch with the necessary change, could you try it with your `hugo` installation?

```sh
quarto add coatless/quarto-webr@test-hugo-md
```

**Comment by coatless** [comment]
Oh, and please make sure to include in the [`hugo.toml`/site config](https://quarto.org/docs/output-formats/hugo.html#site-config) the following:

```toml
[markup.goldmark.renderer]
unsafe=true
```

**Comment by ClaudiuPapasteri** [comment]
It works perfectly. See the result in my [blog post](https://claudiu.psychlab.eu/post/hugo-blogdown-interactive-code-chunk-webr-quarto/) about using your `quarto-webr` extension with Quarto within a blogdown blog built by Hugo. Maybe it can be a good reference for others (didn't fine any other docs or materials on the topic).

**Comment by coatless** [comment]
@ClaudiuPapasteri awesome to hear! Thank you so much for trying it out. I'll merge in the test branch so it should work directly on the main branch.

**Comment by coatless** [comment]
@ClaudiuPapasteri 

P.S. by default, we're already shimming `webr::install()` to `install.packages()`. No need to expose that :) 

I'll also probably try and enable the status header; but, that won't happen until 0.4.1 / dev.

**Comment by coatless** [comment]
@ClaudiuPapasteri in main now. Thanks again for raising the issue and writing up the post!
