### ISSUE TITLE
[Bug]: iOS 16.x and earlier versions of Safari do not support `OffscreenCanvas` used by the `webr::canvas()` call.

### ISSUE THREAD

**Issue by mccarthy-m-g** [coatless/quarto-webr#155]
### Bug description

WebR seems to hang up when attempting to run code chunks on iOS. This appears to be a bug or compatibility issue with the extension, since other WebR sites (like the REPL app) work fine.

Here’s a screenshot from Safari of the landing page of the documentation site, showing errors in the console output:

![67F3706A-2035-4547-A705-D35D17774FB7](https://github.com/coatless/quarto-webr/assets/51542091/ff807745-39e2-439d-abc3-8bc53e9195e1)

And another from your recent example of automatic chunks:

![887A974C-7180-4DB6-A978-C19B6DD05C87](https://github.com/coatless/quarto-webr/assets/51542091/aceeb229-9e75-4725-8012-86876250db20)

For both pages the network requests were all fine. The bug seems to be restricted to either running or outputting code results.

### Your environment

- OS: iOS 16.2
- Browser: Safari

**Comment by coatless** [comment]
@mccarthy-m-g thanks for raising the issue. I'm having trouble recreating this on-device, through safari dev tools, or on a simulator. Can you give me a bit more background as to what the iOS device is? iPhone 11/12/13/14? Pro? Max? 

Are you using any privacy guards on the device? Are there any third part extensions active? 

> [!NOTE]
Please do note that we operate under the `"PostMessage"` model by default; whereas the docs.r-wasm.org is being run using `"SharedArrayBuffers"`.  The only `null` that can be triggered is if we're looking at the blob outcome for a service-worker mapping; but, that is only present when webR is initialized and isn't needed.

## On-device iPhone 11 Pro Max

https://github.com/coatless/quarto-webr/assets/833642/9d610454-76ee-4587-955b-137361e2634a

# Via Safari Devtools re-creating iOS agent

https://github.com/coatless/quarto-webr/assets/833642/1af63925-4414-495c-ae47-9ac28b37e582

# Via Xcode iOS simulator

https://github.com/coatless/quarto-webr/assets/833642/b60a792d-28ef-4ee0-bcd7-3d35eb18bd41

**Comment by mccarthy-m-g** [comment]
Ah, so it might be a me problem. I'll try to do some more testing to see if I can get it working on my phone.

## More environment details

Phone: iPhone SE (2nd generation model)

These options are all turned on in Safari's privacy and security settings:

- Prevent cross-site tracking
- Fraudulent website warning
- Privacy preserving ad measurement
- Check for Apple pay
- The "Block pop-ups" setting under General

For extensions, I have the following installed:

- AdGuard
- Makeover
- PiPifier
- Sink It for Reddit
- Web Inspector

I'm also using AdGuard's DNS in the General > VPNs, DNS, and Device Management settings.

## Testing

Making the following changes together did not work:

- Clearing cookies from the document site
- Whitelisting the documentation site in AdGuard
- Changing DNS to automatic
- Turning off Block pop-ups

**Comment by coatless** [comment]
@mccarthy-m-g I was able to repro this under iOS 16 and earlier across any iPhone.

The reason why the run code button spins forever is due to the version of Safari included on iOS 16 that omits support for `OffScreenCanvas` that is being employed by {webR}'s `webr::canvas()` function that we use. Earlier version's of {webR} (pre-0.2.0), used a different rendering method. So, if we use either the webR REPL or one of the inline console editors made available on the plotting page, we'll run into a similar issue; except, the handling of it is through a text message instead of never-ending spinning. 

<img width="600" alt="Demo of unsupported action on plotting in a code area with plots enabled" src="https://github.com/coatless/quarto-webr/assets/833642/e2b004ca-11e3-411f-950e-ecc596f2f02f">

<img width="600" alt="Demo of unsupported action on plotting within the webR repl" src="https://github.com/coatless/quarto-webr/assets/833642/0b6c6f49-204f-4075-b453-f60b01c23f55">

Main error message is: 

> WebRWorkerError: This browser does not have support for OffscreenCanvas rendering. Consider instead using a bitmap graphics device, such as png().

So, the main action items here are twofold: 

1. Please upgrade to iOS 17 or later to gain the render ability in Safari. 
2. We need to patch the error condition to avoid the computation from cycling.

**Comment by coatless** [comment]
@mccarthy-m-g to give you an update, I'm waiting for `{webR}` v0.2.3 to be released as it includes better handling for images. c.f. https://github.com/r-wasm/webr/pull/359

**Comment by coatless** [comment]
So, with the {webR} v0.3.1 release and the subsequent {quarto-webr} extension bump to v0.4.1, we now have webR errors regarding [`OffScreenCanvas`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) propagating into the code cell output error when a browser doesn't support the canvas type.

<img width="600" alt="OffScreenCanvas error propagation with {webR} v0.3.1 and {quarto-webr} v0.4.1" src="https://github.com/coatless/quarto-webr/assets/833642/b6fe152e-4ea9-41a5-b391-4789f13a59c0">

With this change, I think the code cells are now addressed.

**Comment by mccarthy-m-g** [comment]
Awesome, looks great! Would it possible to add some text making it clearer that the unsupported environment in question is the user’s browser?

Maybe something less technical like “This browser is not supported by the Quarto webR extension.”

**Comment by coatless** [comment]
Something like: 

<img width="761" alt="Example disclaimer about webR support" src="https://github.com/coatless/quarto-webr/assets/833642/c0e100ec-666c-4aa2-93d1-5c9efbe1962a">

**Comment by mccarthy-m-g** [comment]
Yeah, I like that a lot. Just a small typo in the second sentence to fix: “Please upgrade your *a* web browser…”

**Comment by coatless** [comment]
Okidokie, one more update...

Instead of the `Error: This environment ... ` text that wasn't clear about resolution and went off screen, we now display a message stating graphs will not be displayed at the top of the document. Moreover, we now allow for non-graphical computation and results to propagate. This should bring the cell more in-line with the desired output.

Standard HTML page:

<img width="571" alt="Screenshot of a warning splash on a Quarto HTML Document if `OffScreenCanvas` is not available alongside allowing non-graphical computation results to propagate" src="https://github.com/coatless/quarto-webr/assets/833642/03c3941e-edda-491b-a7f0-f2f2ebab8c4b">

RevealJS slides
<img width="571" alt="Screenshot of a warning splash on a Quarto RevealJS presentation if `OffScreenCanvas` is not available alongside allowing non-graphical computation results to propagate" src="https://github.com/coatless/quarto-webr/assets/833642/59348a79-859b-4da6-bd92-6072374dcc42">
