### ISSUE TITLE
Can webr and shinylive work together in a quarto document?

### ISSUE THREAD

**Issue by royfrancis** [coatless/quarto-webr#167]
### What's your question?

Shinylive and webr quarto extensions seem to work when used independently. But, if I include both of them in the same document, only webr works. Is that expected behavior?

**Comment by royfrancis** [comment]
Never mind! It seems to be working in a clean new environment. It is probably something to do with my project.

**Comment by coatless** [comment]
Yes, the {quarto-shinylive} and {quarto-webr} extension should be embeddable and work together in harmony in the same document. However, they will use different webR instances since shinylive applications are sandboxed to their application and will not share any variables. 

Here's a MWE that shows a shinylive app via `{quarto-shinylive}` working alongside of `{quarto-webr}`:

https://github.com/coatless-tutorials/quarto-webr-with-quarto-shinylive
