### ISSUE TITLE
Progress bar for startup and code execution status

### ISSUE THREAD

**Issue by jooyoungseo** [coatless/quarto-webr#17]
Progress bar indicator would be useful for users to get a better sense of how long they have to wait. Along with visual progress bar, we could consider adding incremental sound to non-visually indicate its progression.

**Comment by jimjam-slam** [comment]
It would be lovely to define where on the page the WebR status indicator gets inserted (in the same way that a [website listing can have an `id` specified](https://quarto.org/docs/websites/website-listings.html#listing-location) to insert into), so that you could quickly make it a sticky element if needed!

**Comment by coatless** [comment]
The `id` portion would be interesting; but, I'm not sure there is an easy way to have a "default" location that is still inside the `<header>` region. The later part would likely need format overrides due to lack of a `title-only` option in [`quarto.doc.include_text()`](https://quarto.org/docs/extensions/lua-api.html#includes)).

Code cell-wise, we're likely going to move to using a "Green" play button that gets replaced with a spinning wheel when code is executing:

https://fontawesome.com/icons/play?f=classic&s=solid&pc=%230d9c29

https://fontawesome.com/icons/spinner?f=classic&s=solid&an=spin

Unfortunately, there isn't a good way of understanding _where_ in a calculation we are when sending code over to webR.

**Comment by jimjam-slam** [comment]
Nah, that makes sense!

**Comment by coatless** [comment]
In v0.3.7, we added a "Green" play button next to Run Code and a spinning wheel for active code cells/package installation. So, I'm going to aim to close out this ticket.
