### ISSUE TITLE
[Q&A]: Will quarto html parameter 'embed-resources' include js-files needed to run webR-extension chunks when using channel type "automatic"?

### ISSUE THREAD

**Issue by mskyttner** [coatless/quarto-webr#62]
### What's your question?

I read [here](https://quarto.org/docs/reference/formats/html.html#rendering) about 'embed-resources' not always being able to include .js-files. Often my goal is to have a standalone .html rendered from quarto, that can be sent as one file to recipients or web servers / buckets. To understand whether the extension works seemlessly with the 'embed-resources' flag is my goal / reason for asking the question. 

I also wonder if there is a way to have regular chunks write data that webR chunks can read over http(s) ie pastebin style data access... what would be a good pattern/strategy without installing too many webR packages?

**Comment by coatless** [comment]
@mskyttner 

Regarding the first question, I do not believe that we'll see the `embed-resources` option work for the `quarto-webr` as I'm not sure we can embed the WASM files. If the `'service-worker'` communication channel is being used, no matter what we'll need to have at least two external files present.

For the second question, could you clarify a bit more what you mean? Is it reflecting persistent storage of input values or?

**Comment by coatless** [comment]
For the equation render issue, this is because the document YAML uses the `embed-resources: true` key.  This has nothing to do with `quarto-webr`.

Regarding including embedded document data, the `webr-r` code cell only handles _R_ code. You would have to write some custom JS inside of a raw HTML code cell to load the exported document data into webR's [virtual file system (VFS) system](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#fs), e.g. `webR.FS.writeFile()` & `webR.FS.readFile()`. From there, it could be loaded using regular R code. Or, you could load the data directly into the global environment while placing it in the VFS system.

**Comment by coatless** [comment]
I'm going to close out the question as being answered. If you end up writing the raw code cell, feel free to let me know!

I would suggest at this point creating a repository that contains the data sets, c.f.

https://github.com/coatless/raw-data

Enable the "GitHub Pages" option with default settings so that each data set is available at a URL like:

```
https://<username>.github.io/<repository>/<dataset>.csv
```

Then, using the `read.csv()` inside of a `{webr-r}` code cell to read in the data, e.g. 

````md
```{webr-r}
df = read.csv("https://coatless.github.io/raw-data/pima.csv")
```
````

**Comment by coatless** [comment]
With #168, you can use `embed-resources` if you are **not** using the `service-worker` communication channel.
