### ISSUE TITLE
Installation problem on ubuntu

### ISSUE THREAD

**Issue by ielbadisy** [coatless/quarto-webr#87]
**Environment Information:**
- OS: Ubuntu 20.04
- Machine: elbadisy-Precision-3560
- Location: ~/Desktop/Recordings/quarto-webr
- Tool/Software: Quarto

**Description:**
When attempting to use the command `quarto add coatless/quarto-webr`, the system returned an error indicating that the command `add` is not recognized.

**Exact Error Message:**
```
ERROR: Unknown command "add". Did you mean command "run"?
```
Do you have an idea how can I fix this? 

Thanks for the nice project, by the way. 

Imad

**Comment by coatless** [comment]
@ielbadisy I think the version of Quarto installed is outdated. 

Could you please make sure you have at least Quarto v1.2+? 

You should be able to see what version of Quarto you have by typing into Terminal:

```
quarto --version
```

You can get an updated copy of Quarto by either downloading the latest version of [RStudio](https://posit.co/download/rstudio-desktop/) or by installing a [standalone Quarto version](https://quarto.org/docs/get-started/). 

Though, since you are on Ubuntu, the following should work:

```sh
# Install gdebi if not already
sudo apt-get install gdebi-core

# Download the latest quarto binary
curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb 

# Install the quarto binary
gdebi --non-interactive quarto-linux-amd64.deb

# Remove the installer
rm -f quarto-linux-amd64.deb
```

**Comment by coatless** [comment]
I'm going to go ahead and close out this ticket. Let me know if the suggested solution didn't work and we can continue to troubleshoot.

**Comment by ielbadisy** [comment]
Thank you for your response. I'll try it out and get back to you in a few hours.

**Comment by ielbadisy** [comment]
I'll try it out and get back to you in a few hours.

**Comment by ielbadisy** [comment]
It's working perfectly! 
Thanks

**Comment by coatless** [comment]
Great! Thanks for letting us know.
