### ISSUE TITLE
[Bug]: setup context only runs code not included in an R package

### ISSUE THREAD

**Issue by WillemSleegers** [coatless/quarto-webr#88]
### Bug description

I get a problem saying that a subsequent chunk doesn't know the existence of variables set in the setup chunk. It works if I only have 1 line of code in the setup chunk, but not if I have multiple lines of code.

### Steps to reproduce

````qmd
---
title: "WebR + Monte Carlo estimate"
format: html
webr: 
  show-startup-message: true
  packages: ['tibble', 'dplyr', 'ggplot2']
  autoload-packages: true
filters:
  - webr
---

```{webr-r}
#| context: setup
s <- 1000
theme_set(theme_minimal())
blue <- "#327291"
```

```{webr-r}
mean <- 5
sd <- 2
n <- 100

data <- tibble(x = rnorm(n = n, mean = mean, sd = sd))

ggplot(data, aes(x = x)) +
  geom_histogram(
    color = "gray20",
    linewidth = 0.25,
    fill = blue,
    alpha = .85
  )
```
````

### Your environment

- IDE: VS Code Version: 1.84.0 (Universal)
- OS: macOS 14.0 (23A344)

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by coatless** [comment]
@WillemSleegers thanks for the report! So, the issue here is the `setup` context is running R code; but is running it out of sync concerning the library load statements. 

We can see that this is the case since multiple variables are being set and, then, revealed in a later context here:
 
https://quarto-webr.thecoatlessprofessor.com/tests/qwebr-test-internal-cell.html

That said, the fix for this is a bit more involved.

**Comment by coatless** [comment]
@WillemSleegers just to give you an update. I'll likely aim to fix this issue next week as the latest version of webR just was released and we updated the internals to use it.

With this in mind, the fix for non-interactive cells bleeding with interactive cells was a bit more involved. I spent some time developing a new approach that should work well. I'm going to do a soft launch of the new way I'm aiming to handle hidden cells in another Quarto extension.

**Comment by coatless** [comment]
@WillemSleegers I rewrote how non-interactive cells are handled in #120. They should now respect the `packages` key completely.

![demo-non-interactive-setup-with-ggplot2-webr](https://github.com/coatless/quarto-webr/assets/833642/d4639812-1771-4a66-8169-f79d80f53fef)


Care to give it a go and let me know if something else is amiss? 

```sh
quarto add coatless/quarto-webr@cell-state-manager
```

**Comment by WillemSleegers** [comment]
Looks like it's working, thanks!

**Comment by coatless** [comment]
@WillemSleegers awesome! Let me know if anything else comes up. 

The next official version should be rolled out next week with a few more features that include this change. Feel free to use the main branch in the interim. 

```
quarto add coatless/quarto-webr
```
